git:
  depth: 1

language: c
compiler: gcc
os: linux
dist: trusty
sudo: require

install:
  - autoreconf -W portability -visf

before_script:
  - ./test/ci/setup.sh

script:
  - ./test/ci/build.sh

env:
  matrix:
    - KEEPALIVED_CONFIG_ARGS=""
    - KEEPALIVED_CONFIG_ARGS="--enable-snmp --enable-snmp-rfc --enable-json --enable-dbus --disable-checksum-compat"
    - KEEPALIVED_CONFIG_ARGS="--enable-sha1 --enable-dbus --enable-dbus-create-instance --disable-dynamic-linking --disable-fwmark --disable-lvs-syncd"
    - KEEPALIVED_CONFIG_ARGS="--enable-dynamic-linking --disable-vrrp-auth --enable-snmp-rfc --disable-snmp-reply-v3-for-v2"
    - KEEPALIVED_CONFIG_ARGS="--disable-libiptc --disable-libipset --disable-libnl"
    - KEEPALIVED_CONFIG_ARGS="--enable-conversion-checks --enable-stacktrace --enable-mem-check --enable-mem-check-log --disable-lvs-64bit-stats"
    - KEEPALIVED_CONFIG_ARGS="--disable-lvs --enable-snmp-vrrp --enable-snmp-rfc --enable-json --enable-sha1 --enable-dbus --disable-routes"
    - KEEPALIVED_CONFIG_ARGS="--disable-vrrp --enable-snmp-checker --enable-json --enable-sha1 --enable-dbus"
    - KEEPALIVED_CONFIG_ARGS="--disable-hardening --enable-dump-threads --enable-select-debug --enable-timer-debug"
